######################
# Site configuration #
######################
title: Podcasts
description: "I’m John Peart. I’m a policy professional with an interest in technology, services and diversity. I write about all sorts of things, and I build things in code."
author: "John Peart"

baseurl: "/podcast" # the subpath of your site, e.g. /blog
url: "https://www.johnpe.art"

####################
# Feature settings #
####################
menu-subdomain: true
menu-header: true
menu-footer: true
analytics: false

###############
# Asset paths #
###############
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"
social-media-image: "/assets/images/site/social-media.png"
favicon: "/favicon.ico"
favicon-svg: "/assets/images/site/favicon.svg"
favicon-pinned-svg: "/assets/images/site/favicon-pinned-svg.svg"
favicon-large-png: "/assets/images/site/favicon-large-png.png"
theme-colour: "#009fe3"

#######################
# <link rel="me" ...> #
#######################
# Twitter
twitter-url: "https://twitter.com/johnpeart" # Twitter handle i.e. joebloggs
twitter-handle: "johnpeart" # Twitter handle i.e. joebloggs
# Mastodon
mastodon-url: "https://mastodon.social/@johnpeart"
mastodon-handle: "johnpeart@mastodon.social"
# Github
github-url:  "https://github.com/johnpeart"
github-handle:  "johnpeart"

##################
# Build settings #
##################
remote_theme: johnpeart/theme
permalink: pretty
markdown: kramdown
future: false
highlighter: rouge
sass:
  sass_dir: _sass

plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from

remote_theme: johnpeart/theme